version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bd
    ports:
      - "3307:3306"
  app:
    container_name: app-tingeso
    image: joakinroa151/app-tingeso:latest
    ports:
      - '8080:8080'
    environment:
      DB_URL: jdbc:mysql://mysql-db:3306/bd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      DB_USERNAME: root
      DB_PASSWORD: password
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
volumes:
  mysql-data: